export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_TECHNICAL_CHARACTERISTIC_SUCCESS = 'LOAD_TECHNICAL_CHARACTERISTIC_SUCCESS';

export const LOAD_COUNTS = 'LOAD_COUNTS';
export const LOAD_COUNTS_SUCCESS = 'LOAD_COUNTS_SUCCESS';

export const LOAD_DATA = 'LOAD_DATA_FOR_COUNT';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';

export const FILTER_DATA_BY_PLACE = 'FILTER_DATA_BY_PLACE';

export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const CHECKING_IS_USER_LOGED_IN = "CHECKING_IS_USER_LOGED_IN";
export const USER_IS_LOGGED_IN = "USER_IS_LOGGED_IN";
export const USER_IS_NOT_LOGGED_IN = "USER_IS_NOT_LOGGED_IN";

