export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_COUNTS = 'LOAD_COUNTS';
export const LOAD_COUNTS_SUCCESS = 'LOAD_COUNTS_SUCCESS';

export const LOAD_DATA = 'LOAD_DATA_FOR_COUNT';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
