export const LOAD_COUNTS = 'LOAD_COUNTS';
export const LOAD_DATA_FOR_DATE = 'LOAD_DATA_FOR_DATE';
export const LOAD_DATA_FOR_COUNT = 'LOAD_DATA_FOR_COUNT';
export const LOAD_DATA_FOR_COUNT_SUCCES = 'LOAD_DATA_FOR_COUNT_SUCCES';
export const LOAD_DATA_SUCCESS = 'LOAD_DATA_SUCCESS';
export const LOAD_COUNTS_SUCCESS = 'LOAD_COUNTS_SUCCESS';